services:
  - type: web
    name: financial-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: "3.10.12"
    envVars:
      - key: OPENDART_API_KEY
        sync: false
      - key: OPENDART_BASE_URL
        value: https://opendart.fss.or.kr/api